/**
 * API Documentation Generator
 *
 * Subcommands:
 *   aiox api-docs                        — Generate API docs (stdout)
 *   aiox api-docs --format markdown      — Output as markdown
 *   aiox api-docs --format json          — Output as JSON
 *   aiox api-docs --output docs/api.md   — Write to file
 *
 * @module cli/commands/api-docs
 * @version 1.0.0
 * @story 16.3 — API Documentation Generator
 */

'use strict';

const fs = require('fs');
const path = require('path');

// ── Constants ────────────────────────────────────────────────────────────────

const HELP_TEXT = `
API DOCUMENTATION GENERATOR

USAGE:
  aiox api-docs                        Generate API docs to stdout (markdown)
  aiox api-docs --format markdown      Output as markdown
  aiox api-docs --format json          Output as JSON
  aiox api-docs --output docs/api.md   Write output to file
  aiox api-docs --help                 Show this help

EXAMPLES:
  aiox api-docs --format json --output docs/api.json
  aiox api-docs --format markdown --output docs/api.md
`.trim();

// ── Extraction ───────────────────────────────────────────────────────────────

/**
 * Extract command registrations from bin/aiox.js content.
 * Looks for patterns like:
 *   case 'commandName': {
 *     // Description — Story X.Y
 *
 * @param {string} content - File content of bin/aiox.js
 * @returns {object[]} Array of { name, description, story }
 */
function extractCommands(content) {
  const commands = [];
  const lines = content.split('\n');

  for (let i = 0; i < lines.length; i++) {
    const caseMatch = lines[i].match(/^\s*case\s+'([^']+)':\s*\{?\s*$/);
    if (caseMatch) {
      const name = caseMatch[1];
      // Look at next line for comment description
      const nextLine = (lines[i + 1] || '').trim();
      if (nextLine.startsWith('//')) {
        const commentText = nextLine.replace(/^\/\/\s*/, '');
        const storyMatch = commentText.match(/Story\s+([\d.]+)/);
        const description = commentText.replace(/\s*—\s*Story\s+[\d.]+/, '').trim();
        commands.push({
          name,
          description,
          story: storyMatch ? storyMatch[1] : null,
        });
      } else {
        commands.push({ name, description: '', story: null });
      }
    }
  }

  return commands;
}

/**
 * Read bin/aiox.js and extract commands.
 * @returns {object[]}
 */
function extractCommandsFromFile() {
  const aioxPath = path.join(process.cwd(), 'bin', 'aiox.js');
  if (!fs.existsSync(aioxPath)) {
    return [];
  }
  const content = fs.readFileSync(aioxPath, 'utf8');
  return extractCommands(content);
}

// ── Formatters ───────────────────────────────────────────────────────────────

/**
 * Format commands as Markdown.
 * @param {object[]} commands
 * @returns {string}
 */
function formatMarkdown(commands) {
  const lines = [];
  lines.push('# AIOX CLI API Documentation');
  lines.push('');
  lines.push(`Generated: ${new Date().toISOString()}`);
  lines.push('');
  lines.push(`Total commands: ${commands.length}`);
  lines.push('');
  lines.push('## Commands');
  lines.push('');
  lines.push('| Command | Description | Story |');
  lines.push('|---------|-------------|-------|');

  for (const cmd of commands) {
    const story = cmd.story ? cmd.story : '-';
    lines.push(`| \`${cmd.name}\` | ${cmd.description} | ${story} |`);
  }

  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('*Generated by `aiox api-docs`*');
  return lines.join('\n');
}

/**
 * Format commands as JSON.
 * @param {object[]} commands
 * @returns {string}
 */
function formatJson(commands) {
  return JSON.stringify(
    {
      generated: new Date().toISOString(),
      totalCommands: commands.length,
      commands,
    },
    null,
    2,
  );
}

/**
 * Format commands in the given format.
 * @param {object[]} commands
 * @param {string} format - "markdown" or "json"
 * @returns {string}
 */
function formatOutput(commands, format) {
  switch (format) {
    case 'json':
      return formatJson(commands);
    case 'markdown':
    default:
      return formatMarkdown(commands);
  }
}

// ── Arg Parsing ──────────────────────────────────────────────────────────────

/**
 * Parse --format flag.
 * @param {string[]} args
 * @returns {string}
 */
function parseFormat(args) {
  const idx = args.indexOf('--format');
  if (idx !== -1 && args[idx + 1]) {
    const fmt = args[idx + 1].toLowerCase();
    if (!['markdown', 'json'].includes(fmt)) {
      throw new Error(`Invalid format: ${fmt}. Must be "markdown" or "json".`);
    }
    return fmt;
  }
  return 'markdown';
}

/**
 * Parse --output flag.
 * @param {string[]} args
 * @returns {string|null}
 */
function parseOutput(args) {
  const idx = args.indexOf('--output');
  if (idx !== -1 && args[idx + 1]) {
    return args[idx + 1];
  }
  return null;
}

// ── Main ─────────────────────────────────────────────────────────────────────

/**
 * Main entry point.
 * @param {string[]} args
 */
function runApiDocs(args) {
  if (args.includes('--help') || args.includes('-h')) {
    console.log(HELP_TEXT);
    return;
  }

  let format;
  try {
    format = parseFormat(args);
  } catch (err) {
    console.error(`Error: ${err.message}`);
    process.exitCode = 1;
    return;
  }

  const outputPath = parseOutput(args);
  const commands = extractCommandsFromFile();

  if (commands.length === 0) {
    console.log('No commands found. Ensure bin/aiox.js exists in the project root.');
    return;
  }

  const output = formatOutput(commands, format);

  if (outputPath) {
    const fullPath = path.isAbsolute(outputPath) ? outputPath : path.join(process.cwd(), outputPath);
    const dir = path.dirname(fullPath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
    fs.writeFileSync(fullPath, output, 'utf8');
    console.log(`API documentation written to ${fullPath} (${commands.length} commands, ${format} format)`);
  } else {
    console.log(output);
  }
}

module.exports = {
  runApiDocs,
  extractCommands,
  extractCommandsFromFile,
  formatMarkdown,
  formatJson,
  formatOutput,
  parseFormat,
  parseOutput,
  HELP_TEXT,
};
