/**
 * Database Model Generator Command Module
 *
 * Generates model with validation and test from CLI.
 *
 * Subcommands:
 *   aiox gen-model <name> --fields "id:number,name:string,email:string"
 *   aiox gen-model --list
 *   aiox gen-model <name> --timestamps   -- add createdAt/updatedAt
 *
 * @module cli/commands/gen-model
 * @version 1.0.0
 * @story 28.2 -- Database Model Generator
 */

'use strict';

const fs = require('fs');
const path = require('path');

// ── Constants ───────────────────────────────────────────────────────────────

const VALID_TYPES = ['string', 'number', 'boolean', 'date', 'object', 'array'];

// ── Helpers ─────────────────────────────────────────────────────────────────

/**
 * Convert name to PascalCase.
 * @param {string} name
 * @returns {string}
 */
function toPascalCase(name) {
  if (!name || typeof name !== 'string') return '';
  return name
    .replace(/[-_\s]+(.)?/g, (_, c) => (c ? c.toUpperCase() : ''))
    .replace(/^(.)/, (c) => c.toUpperCase());
}

/**
 * Convert name to camelCase.
 * @param {string} name
 * @returns {string}
 */
function toCamelCase(name) {
  const pascal = toPascalCase(name);
  if (!pascal) return '';
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

/**
 * Parse fields string into array of {name, type} objects.
 * @param {string} str - "id:number,name:string,email:string"
 * @returns {Array<{name: string, type: string}>}
 */
function parseFields(str) {
  if (!str || typeof str !== 'string') return [];
  return str.split(',').map(item => {
    const parts = item.trim().split(':');
    if (parts.length < 2) return null;
    const name = parts[0].trim();
    const type = parts[1].trim().toLowerCase();
    if (!name || !VALID_TYPES.includes(type)) return null;
    return { name, type };
  }).filter(Boolean);
}

/**
 * Get the output directory for generated models.
 * @param {string[]} args
 * @returns {string}
 */
function getOutputDir(args) {
  const idx = args.indexOf('--output');
  if (idx !== -1 && args[idx + 1]) {
    const dir = args[idx + 1];
    return path.isAbsolute(dir) ? dir : path.resolve(process.cwd(), dir);
  }
  return path.resolve(process.cwd(), 'generated', 'models');
}

/**
 * List generated models.
 * @param {string} dir
 * @returns {string[]}
 */
function listModels(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir).filter(f => {
    const full = path.join(dir, f);
    return fs.statSync(full).isDirectory();
  }).sort();
}

/**
 * Get default value for a field type.
 * @param {string} type
 * @returns {string}
 */
function getDefaultValue(type) {
  switch (type) {
    case 'string': return "''";
    case 'number': return '0';
    case 'boolean': return 'false';
    case 'date': return 'null';
    case 'object': return '{}';
    case 'array': return '[]';
    default: return 'null';
  }
}

/**
 * Get validator expression for a field type.
 * @param {string} fieldName
 * @param {string} type
 * @returns {string}
 */
function getValidator(fieldName, type) {
  switch (type) {
    case 'string': return `typeof data.${fieldName} === 'string'`;
    case 'number': return `typeof data.${fieldName} === 'number' && !isNaN(data.${fieldName})`;
    case 'boolean': return `typeof data.${fieldName} === 'boolean'`;
    case 'date': return `data.${fieldName} === null || data.${fieldName} instanceof Date || typeof data.${fieldName} === 'string'`;
    case 'object': return `typeof data.${fieldName} === 'object' && data.${fieldName} !== null && !Array.isArray(data.${fieldName})`;
    case 'array': return `Array.isArray(data.${fieldName})`;
    default: return 'true';
  }
}

/**
 * Generate model.js content.
 * @param {string} name
 * @param {Array<{name: string, type: string}>} fields
 * @param {boolean} timestamps
 * @returns {string}
 */
function generateModel(name, fields, timestamps) {
  const pascal = toPascalCase(name);

  const allFields = [...fields];
  if (timestamps) {
    allFields.push({ name: 'createdAt', type: 'date' });
    allFields.push({ name: 'updatedAt', type: 'date' });
  }

  const defaults = allFields.map(f => `    ${f.name}: ${getDefaultValue(f.type)},`).join('\n');

  const validationChecks = allFields.map(f => {
    return `  if (data.${f.name} !== undefined && !(${getValidator(f.name, f.type)})) {
    errors.push('${f.name} must be of type ${f.type}');
  }`;
  }).join('\n');

  const timestampCreate = timestamps ? `
  if (data.createdAt === undefined) {
    data.createdAt = new Date().toISOString();
  }
  if (data.updatedAt === undefined) {
    data.updatedAt = new Date().toISOString();
  }` : '';

  return `/**
 * ${pascal} Model
 * Generated by aiox gen-model
 *
 * Fields: ${allFields.map(f => f.name + ':' + f.type).join(', ')}
 */

'use strict';

/**
 * Default values for ${pascal}.
 */
const DEFAULTS = {
${defaults}
};

/**
 * Validate ${pascal} data.
 * @param {Object} data
 * @returns {{ valid: boolean, errors: string[] }}
 */
function validate(data) {
  const errors = [];
  if (!data || typeof data !== 'object') {
    return { valid: false, errors: ['Data must be an object'] };
  }
${validationChecks}
  return { valid: errors.length === 0, errors };
}

/**
 * Create a new ${pascal} instance with defaults.
 * @param {Object} data
 * @returns {Object}
 */
function create(data) {
  const merged = { ...DEFAULTS, ...data };${timestampCreate}
  const result = validate(merged);
  if (!result.valid) {
    throw new Error('Validation failed: ' + result.errors.join(', '));
  }
  return merged;
}

module.exports = {
  DEFAULTS,
  validate,
  create,
};
`;
}

/**
 * Generate model.test.js content.
 * @param {string} name
 * @param {Array<{name: string, type: string}>} fields
 * @param {boolean} timestamps
 * @returns {string}
 */
function generateModelTest(name, fields, timestamps) {
  const pascal = toPascalCase(name);

  return `/**
 * Tests for ${pascal} Model
 * Generated by aiox gen-model
 */

'use strict';

const model = require('./model');

describe('${pascal} Model', () => {
  describe('DEFAULTS', () => {
    it('has default values for all fields', () => {
      expect(model.DEFAULTS).toBeDefined();
      expect(typeof model.DEFAULTS).toBe('object');
    });
  });

  describe('validate', () => {
    it('returns valid for correct data', () => {
      const result = model.validate(model.DEFAULTS);
      expect(result.valid).toBe(true);
      expect(result.errors).toEqual([]);
    });

    it('returns invalid for null data', () => {
      const result = model.validate(null);
      expect(result.valid).toBe(false);
    });

    it('returns invalid for non-object', () => {
      const result = model.validate('string');
      expect(result.valid).toBe(false);
    });
  });

  describe('create', () => {
    it('creates instance with defaults', () => {
      const instance = model.create({});
      expect(instance).toBeDefined();
    });

    it('overrides defaults with provided data', () => {
      const instance = model.create(model.DEFAULTS);
      expect(instance).toBeDefined();
    });

    it('throws on invalid data', () => {
      expect(() => model.create({ ${fields.length > 0 ? fields[0].name + ": Symbol('bad')" : ''} })).toThrow();
    });
  });
});
`;
}

// ── Main Runner ─────────────────────────────────────────────────────────────

/**
 * Run the gen-model command.
 * @param {string[]} args
 */
function runGenModel(args) {
  if (!args || args.length === 0 || args.includes('--help') || args.includes('-h')) {
    console.log('Usage: aiox gen-model <name> [options]');
    console.log('');
    console.log('Options:');
    console.log('  --fields "id:number,name:string"  Define model fields');
    console.log('  --timestamps                      Add createdAt/updatedAt');
    console.log('  --output <dir>                    Custom output directory');
    console.log('  --list                            List generated models');
    console.log('  --help, -h                        Show help');
    return;
  }

  if (args.includes('--list')) {
    const dir = getOutputDir(args);
    const models = listModels(dir);
    if (models.length === 0) {
      console.log('No generated models found.');
      return;
    }
    console.log('Generated models:');
    models.forEach(m => console.log(`  - ${m}`));
    return;
  }

  const name = args[0];
  if (!name || name.startsWith('-')) {
    console.error('Error: model name is required');
    process.exitCode = 1;
    return;
  }

  // Parse fields
  const fieldsIdx = args.indexOf('--fields');
  const fields = fieldsIdx !== -1 ? parseFields(args[fieldsIdx + 1]) : [];

  const timestamps = args.includes('--timestamps');

  // Get output dir
  const outputDir = getOutputDir(args);
  const modelDir = path.join(outputDir, name);

  // Create directory
  fs.mkdirSync(modelDir, { recursive: true });

  // Generate files
  const modelContent = generateModel(name, fields, timestamps);
  const testContent = generateModelTest(name, fields, timestamps);

  fs.writeFileSync(path.join(modelDir, 'model.js'), modelContent, 'utf8');
  fs.writeFileSync(path.join(modelDir, 'model.test.js'), testContent, 'utf8');

  console.log(`Generated model: ${name}`);
  console.log(`  Fields: ${fields.map(f => f.name + ':' + f.type).join(', ') || 'none'}`);
  if (timestamps) console.log('  Timestamps: createdAt, updatedAt');
  console.log(`  Model: ${path.join(modelDir, 'model.js')}`);
  console.log(`  Test:  ${path.join(modelDir, 'model.test.js')}`);
}

module.exports = {
  runGenModel,
  toPascalCase,
  toCamelCase,
  parseFields,
  getOutputDir,
  listModels,
  getDefaultValue,
  getValidator,
  generateModel,
  generateModelTest,
  VALID_TYPES,
};
