github.com:
    users:
        brunajunckes:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: brunajunckes
