/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface DistributionLogicInterface extends utils.Interface {
  functions: {
    "MIN_DONATION()": FunctionFragment;
    "PRECISION()": FunctionFragment;
    "calculateDistribution(uint256,address[])": FunctionFragment;
    "calculatePercentage(uint256,uint256)": FunctionFragment;
    "churchPercentage()": FunctionFragment;
    "donorRewardPercentage()": FunctionFragment;
    "owner()": FunctionFragment;
    "reservePercentage()": FunctionFragment;
    "setDistributionPercentages(uint256,uint256,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "MIN_DONATION"
      | "PRECISION"
      | "calculateDistribution"
      | "calculatePercentage"
      | "churchPercentage"
      | "donorRewardPercentage"
      | "owner"
      | "reservePercentage"
      | "setDistributionPercentages"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "MIN_DONATION",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "PRECISION", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "calculateDistribution",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "calculatePercentage",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "churchPercentage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "donorRewardPercentage",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "reservePercentage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDistributionPercentages",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "MIN_DONATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "PRECISION", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculateDistribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculatePercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "churchPercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "donorRewardPercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reservePercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDistributionPercentages",
    data: BytesLike
  ): Result;

  events: {
    "DistributionConfigUpdated(uint256,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DistributionConfigUpdated"): EventFragment;
}

export interface DistributionConfigUpdatedEventObject {
  church: BigNumber;
  donors: BigNumber;
  reserve: BigNumber;
}
export type DistributionConfigUpdatedEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber],
  DistributionConfigUpdatedEventObject
>;

export type DistributionConfigUpdatedEventFilter =
  TypedEventFilter<DistributionConfigUpdatedEvent>;

export interface DistributionLogic extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DistributionLogicInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    MIN_DONATION(overrides?: CallOverrides): Promise<[BigNumber]>;

    PRECISION(overrides?: CallOverrides): Promise<[BigNumber]>;

    calculateDistribution(
      totalAmount: PromiseOrValue<BigNumberish>,
      donors: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<
      [string[], BigNumber[]] & { recipients: string[]; amounts: BigNumber[] }
    >;

    calculatePercentage(
      amount: PromiseOrValue<BigNumberish>,
      percentage: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    churchPercentage(overrides?: CallOverrides): Promise<[BigNumber]>;

    donorRewardPercentage(overrides?: CallOverrides): Promise<[BigNumber]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    reservePercentage(overrides?: CallOverrides): Promise<[BigNumber]>;

    setDistributionPercentages(
      _church: PromiseOrValue<BigNumberish>,
      _donors: PromiseOrValue<BigNumberish>,
      _reserve: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  MIN_DONATION(overrides?: CallOverrides): Promise<BigNumber>;

  PRECISION(overrides?: CallOverrides): Promise<BigNumber>;

  calculateDistribution(
    totalAmount: PromiseOrValue<BigNumberish>,
    donors: PromiseOrValue<string>[],
    overrides?: CallOverrides
  ): Promise<
    [string[], BigNumber[]] & { recipients: string[]; amounts: BigNumber[] }
  >;

  calculatePercentage(
    amount: PromiseOrValue<BigNumberish>,
    percentage: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  churchPercentage(overrides?: CallOverrides): Promise<BigNumber>;

  donorRewardPercentage(overrides?: CallOverrides): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  reservePercentage(overrides?: CallOverrides): Promise<BigNumber>;

  setDistributionPercentages(
    _church: PromiseOrValue<BigNumberish>,
    _donors: PromiseOrValue<BigNumberish>,
    _reserve: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    MIN_DONATION(overrides?: CallOverrides): Promise<BigNumber>;

    PRECISION(overrides?: CallOverrides): Promise<BigNumber>;

    calculateDistribution(
      totalAmount: PromiseOrValue<BigNumberish>,
      donors: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<
      [string[], BigNumber[]] & { recipients: string[]; amounts: BigNumber[] }
    >;

    calculatePercentage(
      amount: PromiseOrValue<BigNumberish>,
      percentage: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    churchPercentage(overrides?: CallOverrides): Promise<BigNumber>;

    donorRewardPercentage(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    reservePercentage(overrides?: CallOverrides): Promise<BigNumber>;

    setDistributionPercentages(
      _church: PromiseOrValue<BigNumberish>,
      _donors: PromiseOrValue<BigNumberish>,
      _reserve: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "DistributionConfigUpdated(uint256,uint256,uint256)"(
      church?: null,
      donors?: null,
      reserve?: null
    ): DistributionConfigUpdatedEventFilter;
    DistributionConfigUpdated(
      church?: null,
      donors?: null,
      reserve?: null
    ): DistributionConfigUpdatedEventFilter;
  };

  estimateGas: {
    MIN_DONATION(overrides?: CallOverrides): Promise<BigNumber>;

    PRECISION(overrides?: CallOverrides): Promise<BigNumber>;

    calculateDistribution(
      totalAmount: PromiseOrValue<BigNumberish>,
      donors: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculatePercentage(
      amount: PromiseOrValue<BigNumberish>,
      percentage: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    churchPercentage(overrides?: CallOverrides): Promise<BigNumber>;

    donorRewardPercentage(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    reservePercentage(overrides?: CallOverrides): Promise<BigNumber>;

    setDistributionPercentages(
      _church: PromiseOrValue<BigNumberish>,
      _donors: PromiseOrValue<BigNumberish>,
      _reserve: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    MIN_DONATION(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    PRECISION(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    calculateDistribution(
      totalAmount: PromiseOrValue<BigNumberish>,
      donors: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    calculatePercentage(
      amount: PromiseOrValue<BigNumberish>,
      percentage: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    churchPercentage(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    donorRewardPercentage(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    reservePercentage(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setDistributionPercentages(
      _church: PromiseOrValue<BigNumberish>,
      _donors: PromiseOrValue<BigNumberish>,
      _reserve: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
