/**
 * Test Generator Command Module
 *
 * Auto-generates Jest test skeletons for JS modules by parsing module.exports.
 *
 * Subcommands:
 *   aiox test-gen <file>                — generate test skeleton for a module
 *   aiox test-gen <file> --output <path> — write to specific file
 *   aiox test-gen --list <dir>          — list untested modules
 *   aiox test-gen --help                — show help
 *
 * @module cli/commands/test-gen
 * @version 1.0.0
 * @story 18.1 — Test Generator
 */

'use strict';

const fs = require('fs');
const path = require('path');

// ── Constants ────────────────────────────────────────────────────────────────

const HELP_TEXT = `
TEST GENERATOR

USAGE:
  aiox test-gen <file>                 Generate Jest test skeleton for a JS module
  aiox test-gen <file> --output <path> Write skeleton to specific file
  aiox test-gen --list <dir>           List untested modules (no matching .test.js)
  aiox test-gen --help                 Show this help

EXAMPLES:
  aiox test-gen src/utils.js
  aiox test-gen src/utils.js --output tests/utils.test.js
  aiox test-gen --list src/
`.trim();

// ── Helpers ─────────────────────────────────────────────────────────────────

/**
 * Get project root directory.
 * @returns {string}
 */
function getProjectRoot() {
  return process.cwd();
}

/**
 * Parse a JS module file and extract exported function names.
 * Handles: module.exports = { fn1, fn2 }, module.exports.fn = ..., exports.fn = ...
 * @param {string} content - File content
 * @returns {string[]} Array of exported function names
 */
function parseExports(content) {
  const names = new Set();

  // Pattern 1: module.exports = { fn1, fn2, fn3 }
  const objMatch = content.match(/module\.exports\s*=\s*\{([^}]+)\}/);
  if (objMatch) {
    const inner = objMatch[1];
    const items = inner.split(',').map(s => s.trim()).filter(Boolean);
    for (const item of items) {
      // Handle "name" or "name: value" or "name: function"
      const keyMatch = item.match(/^(\w+)/);
      if (keyMatch) {
        names.add(keyMatch[1]);
      }
    }
  }

  // Pattern 2: module.exports.fnName = ...
  const dotExports = content.matchAll(/module\.exports\.(\w+)\s*=/g);
  for (const m of dotExports) {
    names.add(m[1]);
  }

  // Pattern 3: exports.fnName = ...
  const namedExports = content.matchAll(/(?<![.\w])exports\.(\w+)\s*=/g);
  for (const m of namedExports) {
    names.add(m[1]);
  }

  // Pattern 4: module.exports = functionName (single function)
  const singleMatch = content.match(/module\.exports\s*=\s*(\w+)\s*[;\n]/);
  if (singleMatch && !objMatch) {
    const name = singleMatch[1];
    if (name !== 'class' && name !== 'function' && name !== 'new') {
      names.add(name);
    }
  }

  return Array.from(names).sort();
}

/**
 * Generate a Jest test skeleton for given exports.
 * @param {string} modulePath - Relative path to module
 * @param {string[]} exportNames - Exported function names
 * @returns {string} Test file content
 */
function generateSkeleton(modulePath, exportNames) {
  const relImport = modulePath.replace(/\\/g, '/');
  const moduleName = path.basename(modulePath, path.extname(modulePath));

  const lines = [];
  lines.push(`/**`);
  lines.push(` * Tests for ${moduleName}`);
  lines.push(` * Auto-generated by aiox test-gen`);
  lines.push(` */`);
  lines.push(``);
  lines.push(`'use strict';`);
  lines.push(``);

  if (exportNames.length > 0) {
    const destructured = exportNames.join(', ');
    lines.push(`const { ${destructured} } = require('${relImport}');`);
  } else {
    lines.push(`const mod = require('${relImport}');`);
  }

  lines.push(``);
  lines.push(`describe('${moduleName}', () => {`);

  if (exportNames.length === 0) {
    lines.push(`  it('should be defined', () => {`);
    lines.push(`    // TODO: implement test`);
    lines.push(`    expect(mod).toBeDefined();`);
    lines.push(`  });`);
  } else {
    for (const name of exportNames) {
      lines.push(``);
      lines.push(`  describe('${name}', () => {`);
      lines.push(`    it('should be a function', () => {`);
      lines.push(`      // TODO: implement test`);
      lines.push(`      expect(typeof ${name}).toBe('function');`);
      lines.push(`    });`);
      lines.push(``);
      lines.push(`    it('should return expected result', () => {`);
      lines.push(`      // TODO: implement test`);
      lines.push(`    });`);
      lines.push(`  });`);
    }
  }

  lines.push(`});`);
  lines.push(``);

  return lines.join('\n');
}

/**
 * Compute the default test file path for a source file.
 * src/foo.js → src/foo.test.js
 * @param {string} filePath - Source file path
 * @returns {string} Test file path
 */
function defaultTestPath(filePath) {
  const ext = path.extname(filePath);
  const base = filePath.slice(0, -ext.length);
  return `${base}.test${ext}`;
}

/**
 * List untested modules in a directory (no matching .test.js).
 * @param {string} dir - Directory to scan
 * @returns {string[]} Untested module paths (relative to dir)
 */
function listUntested(dir) {
  const root = getProjectRoot();
  const absDir = path.isAbsolute(dir) ? dir : path.join(root, dir);

  if (!fs.existsSync(absDir)) {
    return [];
  }

  const files = [];
  const entries = fs.readdirSync(absDir, { withFileTypes: true });

  for (const entry of entries) {
    if (entry.isFile() && entry.name.endsWith('.js') && !entry.name.endsWith('.test.js') && !entry.name.endsWith('.spec.js')) {
      const testName = entry.name.replace(/\.js$/, '.test.js');
      const testExists = fs.existsSync(path.join(absDir, testName));
      if (!testExists) {
        files.push(entry.name);
      }
    }
  }

  return files.sort();
}

// ── Main Runner ─────────────────────────────────────────────────────────────

/**
 * Run the test-gen command.
 * @param {string[]} argv - Command arguments
 */
function runTestGen(argv) {
  if (!argv || argv.length === 0 || argv.includes('--help') || argv.includes('-h')) {
    console.log(HELP_TEXT);
    return;
  }

  // --list <dir>
  if (argv[0] === '--list') {
    const dir = argv[1] || '.';
    const untested = listUntested(dir);
    if (untested.length === 0) {
      console.log('All modules have tests.');
    } else {
      console.log(`Untested modules in ${dir}:`);
      for (const f of untested) {
        console.log(`  ${f}`);
      }
      console.log(`\nTotal: ${untested.length} untested module(s)`);
    }
    return;
  }

  // test-gen <file> [--output <path>]
  const file = argv[0];
  const root = getProjectRoot();
  const absFile = path.isAbsolute(file) ? file : path.join(root, file);

  if (!fs.existsSync(absFile)) {
    console.error(`Error: File not found: ${file}`);
    process.exitCode = 1;
    return;
  }

  const content = fs.readFileSync(absFile, 'utf8');
  const exportNames = parseExports(content);
  const relPath = path.relative(root, absFile);

  // Determine import path for generated test
  let importPath;
  const outputIdx = argv.indexOf('--output');
  let outputFile;

  if (outputIdx !== -1 && argv[outputIdx + 1]) {
    outputFile = argv[outputIdx + 1];
    const absOutput = path.isAbsolute(outputFile) ? outputFile : path.join(root, outputFile);
    const outputDir = path.dirname(absOutput);
    importPath = './' + path.relative(outputDir, absFile).replace(/\\/g, '/');
  } else {
    // Default: same dir
    importPath = './' + path.basename(absFile);
  }

  const skeleton = generateSkeleton(importPath, exportNames);

  if (outputFile) {
    const absOutput = path.isAbsolute(outputFile) ? outputFile : path.join(root, outputFile);
    const outputDir = path.dirname(absOutput);
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }
    fs.writeFileSync(absOutput, skeleton, 'utf8');
    console.log(`Generated test skeleton: ${outputFile}`);
    console.log(`  Exports found: ${exportNames.length}`);
  } else {
    console.log(skeleton);
  }
}

// ── Exports ─────────────────────────────────────────────────────────────────

module.exports = {
  runTestGen,
  parseExports,
  generateSkeleton,
  defaultTestPath,
  listUntested,
};
