/**
 * Middleware Generator Command Module
 *
 * Generates middleware boilerplate (middleware + test) from CLI.
 *
 * Subcommands:
 *   aiox gen-middleware <name>              -- generate generic middleware
 *   aiox gen-middleware <name> --type auth  -- specific type (auth, logging, validation, cors)
 *   aiox gen-middleware --list              -- list generated middlewares
 *
 * @module cli/commands/gen-middleware
 * @version 1.0.0
 * @story 28.3 -- Middleware Generator
 */

'use strict';

const fs = require('fs');
const path = require('path');

// ── Constants ───────────────────────────────────────────────────────────────

const VALID_TYPES = ['generic', 'auth', 'logging', 'validation', 'cors'];
const DEFAULT_TYPE = 'generic';

// ── Helpers ─────────────────────────────────────────────────────────────────

/**
 * Convert name to PascalCase.
 * @param {string} name
 * @returns {string}
 */
function toPascalCase(name) {
  if (!name || typeof name !== 'string') return '';
  return name
    .replace(/[-_\s]+(.)?/g, (_, c) => (c ? c.toUpperCase() : ''))
    .replace(/^(.)/, (c) => c.toUpperCase());
}

/**
 * Convert name to camelCase.
 * @param {string} name
 * @returns {string}
 */
function toCamelCase(name) {
  const pascal = toPascalCase(name);
  if (!pascal) return '';
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

/**
 * Parse middleware type from args.
 * @param {string} str
 * @returns {string}
 */
function parseType(str) {
  if (!str || typeof str !== 'string') return DEFAULT_TYPE;
  const lower = str.toLowerCase().trim();
  return VALID_TYPES.includes(lower) ? lower : DEFAULT_TYPE;
}

/**
 * Get the output directory for generated middlewares.
 * @param {string[]} args
 * @returns {string}
 */
function getOutputDir(args) {
  const idx = args.indexOf('--output');
  if (idx !== -1 && args[idx + 1]) {
    const dir = args[idx + 1];
    return path.isAbsolute(dir) ? dir : path.resolve(process.cwd(), dir);
  }
  return path.resolve(process.cwd(), 'generated', 'middlewares');
}

/**
 * List generated middlewares.
 * @param {string} dir
 * @returns {string[]}
 */
function listMiddlewares(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir).filter(f => {
    const full = path.join(dir, f);
    return fs.statSync(full).isDirectory();
  }).sort();
}

/**
 * Generate middleware body based on type.
 * @param {string} type
 * @returns {string}
 */
function getMiddlewareBody(type) {
  switch (type) {
    case 'auth':
      return `  const token = req.headers && req.headers.authorization;
  if (!token) {
    res.status(401).json({ error: 'Unauthorized: no token provided' });
    return;
  }
  // TODO: Verify token
  next();`;
    case 'logging':
      return `  const start = Date.now();
  const method = req.method || 'UNKNOWN';
  const url = req.url || '/';
  res.on('finish', () => {
    const duration = Date.now() - start;
    console.log(\`[\${method}] \${url} - \${res.statusCode} (\${duration}ms)\`);
  });
  next();`;
    case 'validation':
      return `  if (!req.body || typeof req.body !== 'object') {
    res.status(400).json({ error: 'Request body must be a valid JSON object' });
    return;
  }
  next();`;
    case 'cors':
      return `  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
  if (req.method === 'OPTIONS') {
    res.status(204).end();
    return;
  }
  next();`;
    default:
      return `  // TODO: Implement middleware logic
  next();`;
  }
}

/**
 * Generate middleware.js content.
 * @param {string} name
 * @param {string} type
 * @returns {string}
 */
function generateMiddleware(name, type) {
  const pascal = toPascalCase(name);
  const camel = toCamelCase(name);
  const body = getMiddlewareBody(type);

  return `/**
 * ${pascal} Middleware (${type})
 * Generated by aiox gen-middleware
 */

'use strict';

/**
 * ${pascal} middleware function.
 * @param {Object} req - Request object
 * @param {Object} res - Response object
 * @param {Function} next - Next middleware
 */
function ${camel}(req, res, next) {
${body}
}

module.exports = { ${camel} };
`;
}

/**
 * Generate middleware.test.js content.
 * @param {string} name
 * @param {string} type
 * @returns {string}
 */
function generateMiddlewareTest(name, type) {
  const pascal = toPascalCase(name);
  const camel = toCamelCase(name);

  let specificTests = '';
  switch (type) {
    case 'auth':
      specificTests = `
  it('returns 401 when no authorization header', () => {
    const req = { headers: {} };
    const res = { status: jest.fn().mockReturnThis(), json: jest.fn() };
    const next = jest.fn();
    mw.${camel}(req, res, next);
    expect(res.status).toHaveBeenCalledWith(401);
    expect(next).not.toHaveBeenCalled();
  });

  it('calls next when token is present', () => {
    const req = { headers: { authorization: 'Bearer token123' } };
    const res = {};
    const next = jest.fn();
    mw.${camel}(req, res, next);
    expect(next).toHaveBeenCalled();
  });`;
      break;
    case 'logging':
      specificTests = `
  it('calls next immediately', () => {
    const req = { method: 'GET', url: '/test' };
    const listeners = {};
    const res = { on: jest.fn((ev, cb) => { listeners[ev] = cb; }), statusCode: 200 };
    const next = jest.fn();
    mw.${camel}(req, res, next);
    expect(next).toHaveBeenCalled();
  });`;
      break;
    case 'validation':
      specificTests = `
  it('returns 400 when body is missing', () => {
    const req = {};
    const res = { status: jest.fn().mockReturnThis(), json: jest.fn() };
    const next = jest.fn();
    mw.${camel}(req, res, next);
    expect(res.status).toHaveBeenCalledWith(400);
    expect(next).not.toHaveBeenCalled();
  });

  it('calls next when body is valid object', () => {
    const req = { body: { key: 'value' } };
    const res = {};
    const next = jest.fn();
    mw.${camel}(req, res, next);
    expect(next).toHaveBeenCalled();
  });`;
      break;
    case 'cors':
      specificTests = `
  it('sets CORS headers', () => {
    const req = { method: 'GET' };
    const res = { setHeader: jest.fn() };
    const next = jest.fn();
    mw.${camel}(req, res, next);
    expect(res.setHeader).toHaveBeenCalledWith('Access-Control-Allow-Origin', '*');
    expect(next).toHaveBeenCalled();
  });

  it('handles OPTIONS preflight', () => {
    const req = { method: 'OPTIONS' };
    const res = { setHeader: jest.fn(), status: jest.fn().mockReturnThis(), end: jest.fn() };
    const next = jest.fn();
    mw.${camel}(req, res, next);
    expect(res.status).toHaveBeenCalledWith(204);
    expect(next).not.toHaveBeenCalled();
  });`;
      break;
    default:
      specificTests = `
  it('calls next for generic middleware', () => {
    const req = {};
    const res = {};
    const next = jest.fn();
    mw.${camel}(req, res, next);
    expect(next).toHaveBeenCalled();
  });`;
  }

  return `/**
 * Tests for ${pascal} Middleware (${type})
 * Generated by aiox gen-middleware
 */

'use strict';

const mw = require('./middleware');

describe('${pascal} Middleware', () => {
  it('exports ${camel} function', () => {
    expect(typeof mw.${camel}).toBe('function');
  });
${specificTests}
});
`;
}

// ── Main Runner ─────────────────────────────────────────────────────────────

/**
 * Run the gen-middleware command.
 * @param {string[]} args
 */
function runGenMiddleware(args) {
  if (!args || args.length === 0 || args.includes('--help') || args.includes('-h')) {
    console.log('Usage: aiox gen-middleware <name> [options]');
    console.log('');
    console.log('Options:');
    console.log('  --type <type>    Middleware type: auth, logging, validation, cors, generic');
    console.log('  --output <dir>   Custom output directory');
    console.log('  --list           List generated middlewares');
    console.log('  --help, -h       Show help');
    return;
  }

  if (args.includes('--list')) {
    const dir = getOutputDir(args);
    const middlewares = listMiddlewares(dir);
    if (middlewares.length === 0) {
      console.log('No generated middlewares found.');
      return;
    }
    console.log('Generated middlewares:');
    middlewares.forEach(m => console.log(`  - ${m}`));
    return;
  }

  const name = args[0];
  if (!name || name.startsWith('-')) {
    console.error('Error: middleware name is required');
    process.exitCode = 1;
    return;
  }

  // Parse type
  const typeIdx = args.indexOf('--type');
  const type = typeIdx !== -1 ? parseType(args[typeIdx + 1]) : DEFAULT_TYPE;

  // Get output dir
  const outputDir = getOutputDir(args);
  const middlewareDir = path.join(outputDir, name);

  // Create directory
  fs.mkdirSync(middlewareDir, { recursive: true });

  // Generate files
  const middlewareContent = generateMiddleware(name, type);
  const testContent = generateMiddlewareTest(name, type);

  fs.writeFileSync(path.join(middlewareDir, 'middleware.js'), middlewareContent, 'utf8');
  fs.writeFileSync(path.join(middlewareDir, 'middleware.test.js'), testContent, 'utf8');

  console.log(`Generated middleware: ${name} (${type})`);
  console.log(`  Middleware: ${path.join(middlewareDir, 'middleware.js')}`);
  console.log(`  Test:       ${path.join(middlewareDir, 'middleware.test.js')}`);
}

module.exports = {
  runGenMiddleware,
  toPascalCase,
  toCamelCase,
  parseType,
  getOutputDir,
  listMiddlewares,
  getMiddlewareBody,
  generateMiddleware,
  generateMiddlewareTest,
  VALID_TYPES,
  DEFAULT_TYPE,
};
