'use strict';

/**
 * AIOX CLI Auto-Complete & Shell Integration
 * Story 6.1 — Generates shell completion scripts for bash, zsh, and fish.
 * Zero external dependencies. CommonJS ES2022.
 */

const fs = require('fs');
const path = require('path');

// All aiox subcommands available for completion
const COMMANDS = [
  'agents', 'palette', 'commands', 'help', 'resume', 'status',
  'telemetry', 'experiment', 'feedback', 'squads',
  'smoke-test', 'changelog', 'health', 'docs',
  'doctor', 'info', 'validate', 'install', 'update',
  'config', 'workers', 'quickstart', 'graph', 'completion',
];

/**
 * Returns the full list of aiox CLI subcommands.
 * @returns {string[]}
 */
function getCommands() {
  return [...COMMANDS];
}

/**
 * Scans the agents directory and returns all agent IDs (from .md filenames).
 * Falls back to a hardcoded list if the directory is unreadable.
 * @param {string} [projectRoot] - Project root path. Defaults to cwd.
 * @returns {string[]}
 */
function getAgentNames(projectRoot) {
  const root = projectRoot || process.cwd();
  const agentsDir = path.join(root, '.aiox-core', 'development', 'agents');

  try {
    const entries = fs.readdirSync(agentsDir);
    const agents = entries
      .filter((e) => e.endsWith('.md'))
      .map((e) => e.replace(/\.md$/, ''))
      .sort();
    if (agents.length > 0) return agents;
  } catch {
    // Fall through to hardcoded list
  }

  return [
    'aiox-master', 'analyst', 'architect', 'data-engineer',
    'dev', 'devops', 'pm', 'po', 'qa', 'sm',
    'squad-creator', 'ux-design-expert',
  ];
}

/**
 * Generates a bash completion script for the aiox CLI.
 * @param {string} [projectRoot] - Project root path.
 * @returns {string}
 */
function generateBashCompletion(projectRoot) {
  const cmds = getCommands().join(' ');
  const agents = getAgentNames(projectRoot).map((a) => `@${a}`).join(' ');

  return `#!/usr/bin/env bash
# AIOX CLI bash completion — generated by aiox completion bash
# Add to ~/.bashrc:  eval "$(aiox completion bash)"

_aiox_completions() {
  local cur="\${COMP_WORDS[COMP_CWORD]}"
  local prev="\${COMP_WORDS[COMP_CWORD-1]}"
  local commands="${cmds}"
  local agents="${agents}"

  case "\${prev}" in
    aiox)
      COMPREPLY=(\$(compgen -W "\${commands}" -- "\${cur}"))
      return 0
      ;;
    completion)
      COMPREPLY=(\$(compgen -W "bash zsh fish install --help" -- "\${cur}"))
      return 0
      ;;
    agents)
      COMPREPLY=(\$(compgen -W "\${agents}" -- "\${cur}"))
      return 0
      ;;
  esac

  COMPREPLY=(\$(compgen -W "\${commands}" -- "\${cur}"))
}

complete -F _aiox_completions aiox
`;
}

/**
 * Generates a zsh completion script for the aiox CLI.
 * @param {string} [projectRoot] - Project root path.
 * @returns {string}
 */
function generateZshCompletion(projectRoot) {
  const cmdEntries = getCommands().map((c) => `    '${c}:${c} command'`).join('\n');
  const agents = getAgentNames(projectRoot).map((a) => `@${a}`).join(' ');

  return `#compdef aiox
# AIOX CLI zsh completion — generated by aiox completion zsh
# Add to ~/.zshrc:  eval "$(aiox completion zsh)"

_aiox() {
  local -a commands
  commands=(
${cmdEntries}
  )

  local -a agents
  agents=(${agents})

  _arguments -C \\
    '1:command:->cmds' \\
    '*::arg:->args'

  case "\$state" in
    cmds)
      _describe -t commands 'aiox command' commands
      ;;
    args)
      case "\${words[1]}" in
        completion)
          _values 'shell' bash zsh fish install --help
          ;;
        agents)
          _values 'agent' \${agents}
          ;;
      esac
      ;;
  esac
}

compdef _aiox aiox
`;
}

/**
 * Generates a fish completion script for the aiox CLI.
 * @param {string} [projectRoot] - Project root path.
 * @returns {string}
 */
function generateFishCompletion(projectRoot) {
  const lines = ['# AIOX CLI fish completion — generated by aiox completion fish',
    '# Save to ~/.config/fish/completions/aiox.fish',
    '',
    '# Disable file completions for aiox',
    'complete -c aiox -f',
    '',
    '# Subcommands',
  ];

  for (const cmd of getCommands()) {
    lines.push(`complete -c aiox -n '__fish_use_subcommand' -a '${cmd}' -d '${cmd} command'`);
  }

  lines.push('');
  lines.push('# completion subcommands');
  for (const sub of ['bash', 'zsh', 'fish', 'install', '--help']) {
    lines.push(`complete -c aiox -n '__fish_seen_subcommand_from completion' -a '${sub}'`);
  }

  lines.push('');
  lines.push('# agent names');
  for (const agent of getAgentNames(projectRoot)) {
    lines.push(`complete -c aiox -n '__fish_seen_subcommand_from agents' -a '@${agent}'`);
  }

  lines.push('');
  return lines.join('\n');
}

/**
 * Detects the current user shell.
 * @returns {string} One of 'bash', 'zsh', 'fish', or 'unknown'.
 */
function detectShell() {
  const shell = process.env.SHELL || '';
  if (shell.includes('zsh')) return 'zsh';
  if (shell.includes('fish')) return 'fish';
  if (shell.includes('bash')) return 'bash';
  return 'unknown';
}

/**
 * Installs the completion script for the detected shell.
 * @param {string} [projectRoot] - Project root path.
 * @returns {{ shell: string, path: string, instruction: string }}
 */
function installCompletion(projectRoot) {
  const shell = detectShell();
  const home = process.env.HOME || process.env.USERPROFILE || '';

  switch (shell) {
    case 'bash': {
      const script = generateBashCompletion(projectRoot);
      const dest = path.join(home, '.aiox-bash-completion.sh');
      fs.writeFileSync(dest, script, 'utf8');
      const rcFile = path.join(home, '.bashrc');
      const sourceLine = `\n# AIOX CLI completion\n[ -f "${dest}" ] && source "${dest}"\n`;
      const existing = fs.existsSync(rcFile) ? fs.readFileSync(rcFile, 'utf8') : '';
      if (!existing.includes('.aiox-bash-completion.sh')) {
        fs.appendFileSync(rcFile, sourceLine, 'utf8');
      }
      return { shell, path: dest, instruction: `Source added to ${rcFile}. Run: source ${rcFile}` };
    }
    case 'zsh': {
      const script = generateZshCompletion(projectRoot);
      const dest = path.join(home, '.aiox-zsh-completion.sh');
      fs.writeFileSync(dest, script, 'utf8');
      const rcFile = path.join(home, '.zshrc');
      const sourceLine = `\n# AIOX CLI completion\n[ -f "${dest}" ] && source "${dest}"\n`;
      const existing = fs.existsSync(rcFile) ? fs.readFileSync(rcFile, 'utf8') : '';
      if (!existing.includes('.aiox-zsh-completion.sh')) {
        fs.appendFileSync(rcFile, sourceLine, 'utf8');
      }
      return { shell, path: dest, instruction: `Source added to ${rcFile}. Run: source ${rcFile}` };
    }
    case 'fish': {
      const script = generateFishCompletion(projectRoot);
      const dir = path.join(home, '.config', 'fish', 'completions');
      fs.mkdirSync(dir, { recursive: true });
      const dest = path.join(dir, 'aiox.fish');
      fs.writeFileSync(dest, script, 'utf8');
      return { shell, path: dest, instruction: `Saved to ${dest}. Fish will load it automatically.` };
    }
    default:
      throw new Error(`Cannot detect shell (SHELL=${process.env.SHELL || 'unset'}). Use: aiox completion bash|zsh|fish`);
  }
}

/**
 * Shows help text for the completion command.
 */
function showHelp() {
  console.log(`
AIOX CLI Completion — Shell auto-complete integration

USAGE:
  aiox completion bash      Output bash completion script to stdout
  aiox completion zsh       Output zsh completion script to stdout
  aiox completion fish      Output fish completion script to stdout
  aiox completion install   Detect shell and install completion automatically
  aiox completion --help    Show this help

INSTALLATION:
  # Bash — add to ~/.bashrc:
  eval "$(aiox completion bash)"

  # Zsh — add to ~/.zshrc:
  eval "$(aiox completion zsh)"

  # Fish — save to completions directory:
  aiox completion fish > ~/.config/fish/completions/aiox.fish

  # Auto-detect and install:
  aiox completion install
`);
}

/**
 * CLI handler for the completion command.
 * @param {string[]} argv - Arguments after 'completion' (e.g., ['bash']).
 * @param {string} [projectRoot] - Project root path.
 */
function runCompletion(argv, projectRoot) {
  const sub = (argv && argv[0]) || '';

  switch (sub) {
    case 'bash':
      process.stdout.write(generateBashCompletion(projectRoot));
      break;
    case 'zsh':
      process.stdout.write(generateZshCompletion(projectRoot));
      break;
    case 'fish':
      process.stdout.write(generateFishCompletion(projectRoot));
      break;
    case 'install': {
      try {
        const result = installCompletion(projectRoot);
        console.log(`Shell completion installed for ${result.shell}.`);
        console.log(`File: ${result.path}`);
        console.log(result.instruction);
      } catch (error) {
        console.error(`Error: ${error.message}`);
        process.exit(1);
      }
      break;
    }
    case '--help':
    case '-h':
    case 'help':
    case '':
      showHelp();
      break;
    default:
      console.error(`Unknown completion subcommand: ${sub}`);
      showHelp();
      process.exit(1);
  }
}

module.exports = {
  COMMANDS,
  getCommands,
  getAgentNames,
  generateBashCompletion,
  generateZshCompletion,
  generateFishCompletion,
  detectShell,
  installCompletion,
  showHelp,
  runCompletion,
};
