/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iAaveSol from "./IAave.sol";
export type { iAaveSol };
export type { IERC20 } from "./IERC20";
export type { IGnosisSafe } from "./IGnosisSafe";
