/**
 * API Endpoint Generator Command Module
 *
 * Generates REST endpoint boilerplate (handler + test) from CLI.
 *
 * Subcommands:
 *   aiox gen-endpoint <name>                            -- generate endpoint with GET
 *   aiox gen-endpoint <name> --methods GET,POST,PUT,DELETE  -- specify HTTP methods
 *   aiox gen-endpoint --list                            -- list generated endpoints
 *   aiox gen-endpoint <name> --output <dir>             -- custom output dir
 *
 * @module cli/commands/gen-endpoint
 * @version 1.0.0
 * @story 28.1 -- API Endpoint Generator
 */

'use strict';

const fs = require('fs');
const path = require('path');

// ── Constants ───────────────────────────────────────────────────────────────

const VALID_METHODS = ['GET', 'POST', 'PUT', 'DELETE', 'PATCH'];
const DEFAULT_METHODS = ['GET'];

// ── Helpers ─────────────────────────────────────────────────────────────────

/**
 * Normalize endpoint name to camelCase for function names.
 * @param {string} name
 * @returns {string}
 */
function toCamelCase(name) {
  if (!name || typeof name !== 'string') return '';
  return name
    .replace(/[-_\s]+(.)?/g, (_, c) => (c ? c.toUpperCase() : ''))
    .replace(/^(.)/, (c) => c.toLowerCase());
}

/**
 * Normalize endpoint name to PascalCase for class/module names.
 * @param {string} name
 * @returns {string}
 */
function toPascalCase(name) {
  const camel = toCamelCase(name);
  if (!camel) return '';
  return camel.charAt(0).toUpperCase() + camel.slice(1);
}

/**
 * Parse --methods flag value.
 * @param {string} str - "GET,POST,PUT,DELETE"
 * @returns {string[]}
 */
function parseMethods(str) {
  if (!str || typeof str !== 'string') return DEFAULT_METHODS;
  const methods = str.split(',').map(m => m.trim().toUpperCase()).filter(m => VALID_METHODS.includes(m));
  return methods.length > 0 ? methods : DEFAULT_METHODS;
}

/**
 * Get the output directory for generated endpoints.
 * @param {string[]} args
 * @returns {string}
 */
function getOutputDir(args) {
  const idx = args.indexOf('--output');
  if (idx !== -1 && args[idx + 1]) {
    const dir = args[idx + 1];
    return path.isAbsolute(dir) ? dir : path.resolve(process.cwd(), dir);
  }
  return path.resolve(process.cwd(), 'generated', 'endpoints');
}

/**
 * Get the endpoints directory (for listing).
 * @param {string[]} args
 * @returns {string}
 */
function getEndpointsDir(args) {
  return getOutputDir(args);
}

/**
 * List generated endpoints.
 * @param {string} dir
 * @returns {string[]}
 */
function listEndpoints(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir).filter(f => {
    const full = path.join(dir, f);
    return fs.statSync(full).isDirectory();
  }).sort();
}

/**
 * Generate handler.js content for an endpoint.
 * @param {string} name
 * @param {string[]} methods
 * @returns {string}
 */
function generateHandler(name, methods) {
  const pascal = toPascalCase(name);
  const camel = toCamelCase(name);

  const handlers = methods.map(method => {
    const lower = method.toLowerCase();
    return `/**
 * ${method} /${camel}
 * @param {Object} req - Request object
 * @param {Object} res - Response object
 */
function handle${method.charAt(0) + method.slice(1).toLowerCase()}(req, res) {
  res.status(200).json({ endpoint: '${camel}', method: '${method}' });
}`;
  }).join('\n\n');

  const exports = methods.map(method => {
    return `  handle${method.charAt(0) + method.slice(1).toLowerCase()}`;
  }).join(',\n');

  return `/**
 * ${pascal} Endpoint Handler
 * Generated by aiox gen-endpoint
 *
 * Methods: ${methods.join(', ')}
 */

'use strict';

${handlers}

module.exports = {
${exports},
};
`;
}

/**
 * Generate handler.test.js content for an endpoint.
 * @param {string} name
 * @param {string[]} methods
 * @returns {string}
 */
function generateHandlerTest(name, methods) {
  const pascal = toPascalCase(name);
  const camel = toCamelCase(name);

  const tests = methods.map(method => {
    const fnName = `handle${method.charAt(0) + method.slice(1).toLowerCase()}`;
    return `  describe('${fnName}', () => {
    it('returns 200 with correct payload', () => {
      const req = {};
      const res = { status: jest.fn().mockReturnThis(), json: jest.fn() };
      handler.${fnName}(req, res);
      expect(res.status).toHaveBeenCalledWith(200);
      expect(res.json).toHaveBeenCalledWith({ endpoint: '${camel}', method: '${method}' });
    });
  });`;
  }).join('\n\n');

  return `/**
 * Tests for ${pascal} Endpoint Handler
 * Generated by aiox gen-endpoint
 */

'use strict';

const handler = require('./handler');

describe('${pascal} Endpoint', () => {
${tests}
});
`;
}

// ── Main Runner ─────────────────────────────────────────────────────────────

/**
 * Run the gen-endpoint command.
 * @param {string[]} args - CLI arguments after 'gen-endpoint'
 */
function runGenEndpoint(args) {
  if (!args || args.length === 0 || args.includes('--help') || args.includes('-h')) {
    console.log('Usage: aiox gen-endpoint <name> [options]');
    console.log('');
    console.log('Options:');
    console.log('  --methods GET,POST,PUT,DELETE  Specify HTTP methods (default: GET)');
    console.log('  --output <dir>                 Custom output directory');
    console.log('  --list                         List generated endpoints');
    console.log('  --help, -h                     Show help');
    return;
  }

  if (args.includes('--list')) {
    const dir = getEndpointsDir(args);
    const endpoints = listEndpoints(dir);
    if (endpoints.length === 0) {
      console.log('No generated endpoints found.');
      return;
    }
    console.log('Generated endpoints:');
    endpoints.forEach(e => console.log(`  - ${e}`));
    return;
  }

  const name = args[0];
  if (!name || name.startsWith('-')) {
    console.error('Error: endpoint name is required');
    process.exitCode = 1;
    return;
  }

  // Parse methods
  const methodsIdx = args.indexOf('--methods');
  const methods = methodsIdx !== -1 ? parseMethods(args[methodsIdx + 1]) : DEFAULT_METHODS;

  // Get output dir
  const outputDir = getOutputDir(args);
  const endpointDir = path.join(outputDir, name);

  // Create directory
  fs.mkdirSync(endpointDir, { recursive: true });

  // Generate files
  const handlerContent = generateHandler(name, methods);
  const testContent = generateHandlerTest(name, methods);

  fs.writeFileSync(path.join(endpointDir, 'handler.js'), handlerContent, 'utf8');
  fs.writeFileSync(path.join(endpointDir, 'handler.test.js'), testContent, 'utf8');

  console.log(`Generated endpoint: ${name}`);
  console.log(`  Methods: ${methods.join(', ')}`);
  console.log(`  Handler: ${path.join(endpointDir, 'handler.js')}`);
  console.log(`  Test:    ${path.join(endpointDir, 'handler.test.js')}`);
}

module.exports = {
  runGenEndpoint,
  toCamelCase,
  toPascalCase,
  parseMethods,
  getOutputDir,
  listEndpoints,
  generateHandler,
  generateHandlerTest,
  VALID_METHODS,
  DEFAULT_METHODS,
};
